# eyewitness configuration file

# Enter your own Firefox path to places.sqlite & WAL files, ie:
# "/home/youruser/.mozilla/firefox/sd94b4jk.default-release/places.sqlite"
# "/home/youruser/.mozilla/firefox/sd94b4jk.default-release/places.sqlite-wal"
Places_File = "/places.sqlite"
Places_WAL = "/places.sqlite-wal"

# Enter your own path for desired backup location, ie:
# "/home/youruser/Nextcloud/Backup/eyewitness/"
Backup_Folder = "/eyewitness/"
