# everymark configuration file

# Firefox places.sqlite, ie: "/home/youruser/.mozilla/firefox/sd94b4jk.default-release/places.sqlite"
Places_File = "/home/marcx1/.librewolf/eoohho6a.default-release/places.sqlite"
Places_WAL = "/home/marcx1/.librewolf/eoohho6a.default-release/places.sqlite-wal"

# Location of desired automated backup, example: "/home/youruser/Nextcloud/Backup/everymark/"
Backup_Folder = "/home/marcx1/Nextcloud/Backup/eyewitness/"
